### ISSUE TITLE
Show the user the error messages from DVID

### ISSUE THREAD

**Issue by stuarteberg** [clio-janelia/clio_website#99]
Specifically, we care about schema validation errors that DVID might emit when editing body annotations (such as putting a string in the `group` field, which is usually required to be `integer` or `null`).

[Possibly in this function?](https://github.com/clio-janelia/clio_website/blob/2974b505fb206ba29a33d5b9fd9cc37edeae0c4e/src/Annotation/AnnotationRequest.js#L12)

Test with `emdata7:9000`, or feel free to test on production if you mess with this body: `1113303622`

**Comment by neomorphic** [comment]
Fixed in 56587ecffbc101ecf764ffc4eea695018a8a7005
